FROM openjdk:11.0-jdk 
RUN apt-get update && apt-get install -y fontconfig rsync make vim
COPY simsun.ttc /usr/share/fonts/ttf-dejavu/simsun.ttc
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8
